# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-16 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=500)),
                ('file_viewes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
